```{r}
library(readxl)
neg <- read_excel("C:/Users/LENOVO/Desktop/KAMILA ESTD 2/bases trab/Negocio propio.xlsx")
View(neg)
```

```{r}
summary(neg)
```

```{r}
neg[,c(2:12)]=lapply(neg[,c(2:12)],as.numeric)
```
```{r}
neg=neg[,c(1,5:9)]
```

```{r}
neg2=neg[complete.cases(neg),]
```

```{r}
library(readxl)
emp <- read_excel("C:/Users/LENOVO/Desktop/KAMILA ESTD 2/bases trab/mujeres con empleo.xls")
View(emp)
```
```{r}
emp2=emp[,c(1,55:60)]
```

```{r}
names(emp2)=emp2[3,]
```

```{r}
emp2=emp2[-c(1:3),]
```

```{r}
str(emp2)
```
```{r}
emp2[,c(2:7)]=lapply(emp2[,c(2:7)],as.numeric)
```

# financiera

```{r}
library(readxl)
fin <- read_excel("C:/Users/LENOVO/Desktop/KAMILA ESTD 2/bases trab/Cuenta en institucion financiera.xlsx")
View(fin)
```
```{r}
fin=fin[,c(1,2,5,8)]
```

```{r}
fin[,c(2:4)]=lapply(fin[,c(2:4)],as.numeric)
```
```{r}
str(fin)
```
```{r}
dim(fin)
```

```{r}
fin=fin[-c(264),]
```


```{r}
names(fin)=c("PAIS","FIN_2011","FIN_2014","FIN_2017")
```

```{r}
names(emp2)=c("PAIS","EMP_2010","EMP_2011","EMP_2012","EMP_2013","EMP_2014","EMP_2015")
```

```{r}
names(neg)=c("PAIS","NEG_2014","NEG_2015","NEG_2016","NEG_2017","NEG_2018")
```

```{r}
fin$fin_ratio=apply(fin[,c(2:4)],1,mean,na.rm=TRUE)
```


```{r}
emp2$emp2_ratio=apply(emp2[,c(2:7)],1,mean,na.rm=TRUE)
```


```{r}
neg$neg_ratio=apply(neg[,c(2:6)],1,mean,na.rm=TRUE)
```







```{r}
aux=merge(neg,emp2)
final=merge(aux,fin)
```

```{r}
str(final)
```

